### ISSUE TITLE
Node load problem

### ISSUE THREAD

**Issue by sborys-ai** [JPS-GER/ComfyUI_JPS-Nodes#1]
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/home/sborys/miniconda3/envs/old_python/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/home/sborys/miniconda3/envs/old_python/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/home/sborys/miniconda3/envs/old_python/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/mnt/HDD_1Tb/SDXL/ComfyUI/server.py", line 46, in cache_control
    response: web.Response = await handler(request)
  File "/mnt/HDD_1Tb/SDXL/ComfyUI/server.py", line 416, in get_object_info
    out[x] = node_info(x)
  File "/mnt/HDD_1Tb/SDXL/ComfyUI/server.py", line 395, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "/mnt/HDD_1Tb/SDXL/ComfyUI/custom_nodes/ComfyUI_JPS-Nodes/jps_nodes.py", line 1570, in INPUT_TYPES
    self.json_data_movies, movies = load_styles_from_directory(current_directory + '\styles\movies')
  File "/mnt/HDD_1Tb/SDXL/ComfyUI/custom_nodes/ComfyUI_JPS-Nodes/jps_nodes.py", line 54, in load_styles_from_directory
    json_files = get_all_json_files(directory)
  File "/mnt/HDD_1Tb/SDXL/ComfyUI/custom_nodes/ComfyUI_JPS-Nodes/jps_nodes.py", line 47, in get_all_json_files
    return [os.path.join(directory, file) for file in os.listdir(directory) if file.endswith('.json') and os.path.isfile(os.path.join(directory, file))]
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/HDD_1Tb/SDXL/ComfyUI/custom_nodes/ComfyUI_JPS-Nodes\\styles\\movies'

What can be done about this?

Before the September 12th update, everything was working fine. 
The directories and files do exist at the specified path.

**Comment by JPS-GER** [comment]
Please load the new update and try again. If it doesn't work remove the nodes and install them again. There was a problem in the way the subdirectory was added - it wasn't compatible with Linux.

**Comment by sborys-ai** [comment]
Thanks! It's all good now.
